# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               ClifsProTips
tagline:             'More useful than cat videos. Maybe.'
description:         'Clif is not a pro. His name is not Clif. You have been warned.'
url:                 http://www.clifsprotips.com
#url:                 http://localhost:4000
baseurl:           ''
paginate:            2
gems: [jekyll-paginate]
paginate_path: "page:num"

# About/contact
author:
  name:              Clif
  url:               https://twitter.com/clifsprotips
  email:             info@clifsprotips.com

# Custom vars
version:             1.0.0
